### ISSUE TITLE
Turkish character issue or Culture support

### ISSUE THREAD

**Issue by efeozyer** [leonibr/efcore-snakecase#4]
There is an issue about Turkish latin charachter little 'i' without dot ( 'ı' )..

When I migrate database table and field names generated with ("ı").

Identity_users -> ıdentity_users
User_Info -> user_ınfo

Please add culture option or replcae ("ı") with ("i")

![image](https://user-images.githubusercontent.com/18365191/69787055-954ea980-11b3-11ea-8ed0-e50861a505ea.png)

**Comment by leonibr** [comment]
Hi there,
Could you write some tests with a range of caracteres, like in 
```c#
        [Theory(DisplayName ="Should allow")]
        [InlineData("PersonLogAuditTrail", "person_log_audit_trail")]
        [InlineData("Person_Log", "person_log")]
        [InlineData("_Person_Log", "person_log")]
        [InlineData("Person_1Log", "person_1_log")]
        [InlineData("Person1Log", "person1_log")]
        [InlineData("PersonLOGFile", "person_logfile")]
        [InlineData("PersonCodeId", "person_code_id")]
        [InlineData("PersonAddress_", "person_address_")]
        [InlineData("PırsonAddrëss_", "pırson_addrëss_")]
        public void TestFramatNames(string given, string expcted)
        {
            given.ToSnakeCase().ShouldBe(expcted);
        }
```

**Comment by leonibr** [comment]
Closed by mistake...

**Comment by leonibr** [comment]
no response.

**Comment by efeozyer** [comment]
Could you reopen this issue? I will add some test case

**Comment by leonibr** [comment]
ok, then

**Comment by leonibr** [comment]
I am sorry, I got you wrong, the method does not "replace" any character on source name, what it does is  to find "break points" in words to insert "_"
In the examples you gave like `UserInfo` you probably typed the capital undotted I => `ı I` (UnDotted`I`) instead of the actual capital dotted i -> `iİ` (Dotted İ).
For my keyboard `I` is te capital form of your dotted `İ`, so your Type should be `Userİnfo`, give it a try and let me know
